### ISSUE TITLE
2d fog shader stop moving after some time

### ISSUE THREAD

**Issue by Raklit** [steincodes/godot-shader-tutorials#3]
I have basic problem with 2d dynamic shaders in Godot.
2d fog shader stop moving after some time.
I think it depends on the motion vector and the coordinate overflow.
Where I can see issue without this error?

**Comment by Raklit** [comment]
This was a TIME variable overflow problem. Do not use this variable directly in any shader.

**Comment by realkotob** [comment]
@Raklit What should be used instead?
I'm asking because most shader examples I see online use the TIME variable in some way for animated effects.
